CMPL = gcc
WARN = -Wall
OBJS = a.out
HELP = -h
FRAMES = -f
PROCESSES = -p
PAGES = -v
WS = -w
SECONDS = -s
CICLES = -l
TARGET = *.c
QTD_FRAMES = 64
QTD_PROCESSES = 5
QTD_PAGES = 50
WS_LIMIT = 4
WAIT_TIME = 3
MAX_CICLES = 100000000000
EXE = ./$(OBJS) $(FRAMES)$(QTD_FRAMES) $(PROCESSES)$(QTD_PROCESSES) $(PAGES)$(QTD_PAGES) $(WS)$(WS_LIMIT) $(SECONDS)$(WAIT_TIME) $(CICLES)$(MAX_CICLES)

run:
	$(CMPL) $(TARGET) $(WARN) && $(EXE)

help:
	$(CMPL) $(TARGET) $(WARN) && ./$(OBJS) $(HELP) || true